[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "./whatsmeow-api"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.env]
SKIP_GROUPS = "true"
MAX_MSG_HISTORY = "100"
MAX_RAW_MEDIA_CACHE = "120"
VERBOSE_LOGS = "false"
GOGC = "80"

[[mounts]]
mountPath = "/app/data"
